
name: scalerite
description: basic work order app

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.1
  path: ^1.9.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flutter_localizations:
    sdk: flutter
  http: ^1.3.0
  sqflite_common_ffi: ^2.3.4+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  async: ^2.11.0
  boolean_selector: ^2.1.1
  clock: ^1.1.1
  fake_async: ^1.3.1
  leak_tracker: ^10.0.7
  leak_tracker_flutter_testing: ^3.0.8
  matcher: ^0.12.16
  stack_trace: ^1.12.0
  string_scanner: ^1.3.0
  test_api: ^0.7.3
  vm_service: ^14.3.0

environment:
  sdk: ^3.5.0

flutter:
  uses-material-design: true
